# This docker-compose file sets up ORY Kratos, ORY Hydra, and this app in a network and configures
# in such a way that ORY Kratos is the Login Provider for ORY Hydra.

version: "3.7"

services:
  hydra-migrate:
    image: oryd/hydra:v2.3.0
    depends_on:
      - postgres-hydra
    environment:
      - DSN=postgres://hydra:secret@postgres-hydra:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate -c /etc/config/hydra/hydra.yml sql up -e --yes
    pull_policy: missing
    volumes:
      - type: bind
        source: ./hydra
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet

  hydra:
    image: oryd/hydra:v2.3.0
    depends_on:
      - hydra-migrate
      - postgres-hydra
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./hydra
        target: /etc/config/hydra
    pull_policy: missing
    restart: on-failure
    environment:
      - DSN=postgres://hydra:secret@postgres-hydra:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    environment:
      - PORT=4455
      - SECURITY_MODE=standalone
      - BASE_PATH=/ui
      - HYDRA_ADMIN_URL=http://hydra:4445
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KRATOS_BROWSER_URL=https://auth.gregs-homelab.com
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme

    ports:
      - "4455:4455"
    networks:
      - intranet
    volumes:
      - /tmp/ui-node/logs:/root/.npm/_logs
    restart: on-failure

  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.3.1
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet

  synapse:
    image: docker.io/matrixdotorg/synapse:v1.126.0
#   image: docker.io/library/python:3.12-slim-bookworm
    ports:
      - "8448:8448/tcp"
    restart: on-failure
#    restart: no
#    entrypoint: "ls -la /etc/config/synapse"
    environment:
      SYNAPSE_CONFIG_PATH: /etc/config/synapse/config.yml
      SYNAPSE_NO_TLS: true # todo: remove when https implemented
    volumes:
      - type: volume
        source: synapse-media
        target: /media_store
        read_only: false
      - type: bind
        source: ./synapse
        target: /etc/config/synapse
        read_only: false
    networks:
      - intranet
    depends_on:
      - postgres-synapse

  postgres-hydra:
    image: postgres:16
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet

  postgres-synapse:
    image: postgres:16
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:

volumes:
  kratos-sqlite:
  synapse-media:
